### ISSUE TITLE
Mark support for newer python versions

### ISSUE THREAD

**Issue by ziima** [spoqa/sqlalchemy-utc#15]
Last version supported by the project seems to be 3.6. It seems nothing is blocking the 3.7-3.9, it just needs to be declared and tested.

**Comment by Jhuni0123** [comment]
Newer versions (3.7, 3.8, 3.9) are tested on https://github.com/spoqa/sqlalchemy-utc/pull/12 and marked support on ad887cde10adf9ccabb630dc9f9889ecbc51fbce.
